name: Verilog Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Verilator
        run: sudo apt-get update && sudo apt-get install -y verilator
      - name: Run Lint
        run: make lint
