//------------------------------------------------------------------------------
// Application interface for adder_example register block.
//
// NOTE: This file is autogenerated by regio. DO NOT EDIT.
//------------------------------------------------------------------------------

interface adder_example_reg_intf ();

    import adder_example_reg_pkg::*;

    reg_enable_t enable;
    reg_operand_a_t operand_a;
    reg_operand_b_t operand_b;
    reg_result_t result;
    reg_result_t result_nxt;
    logic result_nxt_v;

    modport controller (
        output enable,
        output operand_a,
        output operand_b,
        output result,
        input result_nxt,
        input result_nxt_v
    );

    modport peripheral (
        input enable,
        input operand_a,
        input operand_b,
        input result,
        output result_nxt,
        output result_nxt_v
    );

endinterface : adder_example_reg_intf
