//------------------------------------------------------------------------------
// Definitions package for adder_example register block.
//
// NOTE: This file is autogenerated by regio. DO NOT EDIT.
//------------------------------------------------------------------------------

package adder_example_reg_pkg;

    // -------------------------------------------------------------
    // Block parameters
    // -------------------------------------------------------------

    localparam int BLOCK_SIZE = 16;
    localparam int BLOCK_ADDR_WID = $clog2(BLOCK_SIZE);

    // -------------------------------------------------------------
    // Register address offsets
    // -------------------------------------------------------------

    localparam int OFFSET_ENABLE                   = 'h00000000;
    localparam int OFFSET_OPERAND_A                = 'h00000004;
    localparam int OFFSET_OPERAND_B                = 'h00000008;
    localparam int OFFSET_RESULT                   = 'h0000000C;

    // -------------------------------------------------------------
    // Register array sizes
    // -------------------------------------------------------------

    localparam int COUNT_ENABLE                   = 1;
    localparam int COUNT_OPERAND_A                = 1;
    localparam int COUNT_OPERAND_B                = 1;
    localparam int COUNT_RESULT                   = 1;

    // -------------------------------------------------------------
    // Register/field definitions
    // -------------------------------------------------------------

    // register: enable
    // description: Enable adder operation
    typedef bit [0:0] reg_enable_t;

    // register: operand_a
    // description: First operand for addition (32-bit)
    typedef bit [31:0] reg_operand_a_t;

    // register: operand_b
    // description: Second operand for addition (32-bit)
    typedef bit [31:0] reg_operand_b_t;

    // register: result
    // description: Addition result (32-bit)
    typedef bit [31:0] reg_result_t;

    // -------------------------------------------------------------
    // Register initialization values
    // -------------------------------------------------------------
    localparam reg_enable_t INIT_ENABLE = 1'h0;
    localparam reg_operand_a_t INIT_OPERAND_A = 32'h0;
    localparam reg_operand_b_t INIT_OPERAND_B = 32'h0;
    localparam reg_result_t INIT_RESULT = 32'h0;

endpackage : adder_example_reg_pkg
