//------------------------------------------------------------------------------
// Verification header file manifest for  register blocks.
//
// NOTE: This file is autogenerated. DO NOT EDIT.
//------------------------------------------------------------------------------

package _reg_verif_pkg;

`include "adder_example_reg_blk_agent.svh"

endpackage : _reg_verif_pkg
